export const GET_GOOGLE = "GET_GOOGLE";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SUGEST_TO_STORE = "SUGEST_TO_STORE";
export const CLEARE_SUGGESTIONS = "CLEARE_SUGGESTIONS";
export const WIKI_TO_STORE = "WIKI_TO_STORE";
export const CLICK_SUGGESTION = 'CLICK_SUGGESTION'