export const GET_GOOGLE = "GET_GOOGLE";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SUGGEST_TO_STORE = "SUGGEST_TO_STORE";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";
export const WIKI_TO_STORE = "WIKI_TO_STORE";
export const CLICK_SUGGESTION = 'CLICK_SUGGESTION'