


export const GET_GOOGLE_PENDING = "GET_GOOGLE_PENDING";
export const GET_GOOGLE_FULFILLED = "GET_GOOGLE_FULFILLED";
export const GET_GOOGLE_REJECTED = "GET_GOOGLE_REJECTED";


export const INPUT_CHANGE = "INPUT_CHANGE";



export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";

export const WIKI_PENDING = "WIKI_PENDING";
export const WIKI_FULFILLED = "WIKI_FULFILLED";
export const WIKI_REJECTED = "WIKI_REJECTED";
export const WIKI_NOTFOUND = "WIKI_NOTFOUND";


export const CLICK_SUGGESTION = 'CLICK_SUGGESTION'