export const GET_GOOGLE = "GET_GOOGLE";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SUGGEST_TO_STORE = "SUGGEST_TO_STORE";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";

export const WIKI_PENDING = "WIKI_PENDING";
export const WIKI_FULFILLED = "WIKI_FULFILLED";
export const WIKI_NOTFOUND = "WIKI_NOTFOUND";


export const CLICK_SUGGESTION = 'CLICK_SUGGESTION'